language: php

sudo: false

php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4, nightly]
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly


cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - bin/phpspec run --no-interaction --format=pretty
