version: '3.9'

services:
  php7.4:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        XDEBUG_VERSION: xdebug-3.1.5
        PHP_VERSION: php:7.4.33-zts-alpine3.16
    volumes:
      - ./src:/var/www/html/src
      - ./tests:/var/www/html/tests
      - ./composer.json:/var/www/html/composer.json

  php8.0:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_VERSION: php:8.0.29-zts-alpine3.16
    volumes:
      - ./src:/var/www/html/src
      - ./tests:/var/www/html/tests
      - ./composer.json:/var/www/html/composer.json

  php8.1:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_VERSION: php:8.1.20-zts-alpine3.18
    volumes:
      - ./src:/var/www/html/src
      - ./tests:/var/www/html/tests
      - ./composer.json:/var/www/html/composer.json

  php8.2:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_VERSION: php:8.2.7-zts-alpine3.18
    volumes:
      - ./src:/var/www/html/src
      - ./tests:/var/www/html/tests
      - ./composer.json:/var/www/html/composer.json

  php-dev:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_VERSION: php:8.2.7-zts-alpine3.18
    command: "tail -F /var/www/html/php_error.log"
    environment:
      PHP_IDE_CONFIG: serverName=behat-test-runner
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src:/var/www/html/src
      - ./tests:/var/www/html/tests
      - ./vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./features:/var/www/html/features
      - ./behat.yml:/var/www/html/behat.yml
